# Generated by Django 4.2.3 on 2023-07-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bus_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bname", models.CharField(max_length=20)),
                ("bdate", models.DateField()),
                ("bprice", models.FloatField()),
                ("bfrom", models.CharField(max_length=20)),
                ("bto", models.CharField(max_length=20)),
            ],
        ),
    ]
